[database]
# db_file kann absolut oder relativ zu diesem Ordner angegeben werden, z.B. db_file = praxis.db
db_file = praxis.db
max_backups = 20

[security]
encryption_key = VmylsZYjVA5f6VMv3PtWtMIeOgbw6aOYyPrM1kiPDps=
use_passphrase = true
passphrase_salt = jzp3wxb1BwfEq1nPdGzqhA==

